# Compresses the json generated by the pdf_parser so that its token efficient to send to the llm

class compressor:

    @staticmethod
    def compress (pages_data: list) -> list:
        pages = []
        for page in pages_data:
            container = []
            for zone in ['headers', 'body', 'footers']:
                for block in page[zone]:
                    id = block['id']
                    type = block['type']
                    if type != 'bordered_box' and type != 'logo_placeholder' and type!='table':
                            render_mode = block['render_mode']
                            render_mode = None
                    else:
                        render_mode = None

                    if 'lines' in block and block['lines']:
                        text = [text['text'] for segment in block['lines'] for text in segment['segments']]
                        text = ' '.join(text)
                    else:
                        text = None
                    container.append({
                        'block_id': id, 
                        'block_type': type, 
                        'render_mode': render_mode, 
                        'text': text
                        })
            pages.append(container)

        return pages

